// Generated by CoffeeScript 1.12.4
var exec, fs, npmBin, path, scriptsDir;

path = require("path");

exec = require("exec");

fs = require("io/sync");

scriptsDir = path.dirname(__dirname);

npmBin = exec.sync("sudo npm bin -g");

module.exports = function() {
  var cachePath;
  cachePath = path.join(scriptsDir, "scripts.json");
  if (fs.exists(cachePath)) {
    require(cachePath).forEach(function(script) {
      var binPath;
      binPath = path.join(npmBin, script);
      return exec.sync("sudo rm " + binPath);
    });
    fs.remove(cachePath);
  }
  return log(exec.sync("sudo node postinstall.js", {
    cwd: scriptsDir
  }));
};
