// Generated by CoffeeScript 1.12.4
var exec, fs, path, prompt;

global.Promise = require("Promise");

prompt = require("prompt");

path = require("path");

exec = require("exec");

fs = require("io/sync");

module.exports = function(args) {
  var dest, globalPath, moduleName, modulePath, npmRoot, shouldDestroy;
  if (!(moduleName = args._[0])) {
    return log.warn("Must provide a module name!");
  }
  if (moduleName[0] === "." || moduleName[0] === "/") {
    return log.warn("Module names cannot start with . or /");
  }
  log.moat(1);
  log.red("Deleting package: ");
  log.white(moduleName);
  log.moat(1);
  log.gray("Are you sure?");
  shouldDestroy = prompt.sync({
    bool: true
  });
  log.moat(1);
  if (!shouldDestroy) {
    return;
  }
  npmRoot = exec.sync("npm root -g");
  globalPath = path.join(npmRoot, moduleName);
  if (fs.isLink(globalPath)) {
    dest = fs.readLink(globalPath);
    modulePath = path.resolve(moduleName);
    if (dest === modulePath) {
      fs.remove(globalPath);
    }
  }
  return fs.remove(moduleName);
};
