// Generated by CoffeeScript 1.12.4
var PureObject, assertType, isType;

PureObject = require("PureObject");

assertType = require("assertType");

isType = require("isType");

module.exports = function(mods) {
  var inverse, json, name;
  assertType(mods, Object.or(PureObject));
  inverse = Object.create(null);
  for (name in mods) {
    json = mods[name].json;
    if (inverse[name] == null) {
      inverse[name] = [];
    }
    if (!isType(json.dependencies, Object)) {
      continue;
    }
    Object.keys(json.dependencies).forEach(function(dep) {
      if (inverse[dep]) {
        return inverse[dep].push(name);
      } else {
        return inverse[dep] = [name];
      }
    });
  }
  return inverse;
};
