// Generated by CoffeeScript 1.12.4
var git, prompt, upstreamError;

prompt = require("prompt");

git = require("git-utils");

module.exports = function(modulePath, options) {
  if (options == null) {
    options = {};
  }
  if (options.remote == null) {
    options.remote = "origin";
  }
  return git.pushBranch(modulePath, options).fail(function(error) {
    if (!upstreamError.test(error.message)) {
      throw error;
    }
    log.moat(1);
    log.yellow("WARN: ");
    log.white("The current branch has no upstream branch!");
    log.moat(1);
    log.gray("Should ");
    log.yellow(options.remote + "/unstable");
    log.gray(" be the upstream branch? ");
    return prompt.async({
      bool: true
    }).then(function(setUpstream) {
      log.moat(1);
      if (!setUpstream) {
        throw Error("Cannot push local branch without an upstream branch!");
      }
      options.upstream = true;
      return git.pushBranch(modulePath, options);
    });
  });
};

upstreamError = /The current branch [^\s]+ has no upstream branch/;
