// Generated by CoffeeScript 1.12.4
var PureObject, assertType, sortModules;

PureObject = require("PureObject");

assertType = require("assertType");

sortModules = function(mods, sort) {
  var count, index, mod, names, sorted;
  assertType(mods, PureObject);
  sorted = [];
  names = Object.keys(mods);
  count = names.length;
  while (count > 0) {
    index = 0;
    while (index < count) {
      mod = mods[names[index]];
      if (sort(mod)) {
        count -= 1;
        names.splice(index, 1);
        sorted.push(mod);
      } else {
        index += 1;
      }
    }
  }
  return sorted;
};

module.exports = sortModules;
